--
-- PostgreSQL database dump
--

\restrict Xq245Z00PuPHL7yuWKhzsormDXDzPhwMm8lonOcMzczwt8ChGDlo4Q0xeVrzII9

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.9 (Ubuntu 17.9-1.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


--
-- Name: join_method; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.join_method AS ENUM (
    'public',
    'request_to_join',
    'private'
);


ALTER TYPE public.join_method OWNER TO postgres;

--
-- Name: TYPE join_method; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TYPE public.join_method IS 'Join method for study groups';


--
-- Name: visibility; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.visibility AS ENUM (
    'private',
    'public'
);


ALTER TYPE public.visibility OWNER TO postgres;

--
-- Name: TYPE visibility; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TYPE public.visibility IS 'Visibility of the study group';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Degree_Program; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Degree_Program" (
    degree_prog_id integer NOT NULL,
    degree_prog_name text NOT NULL
);


ALTER TABLE public."Degree_Program" OWNER TO postgres;

--
-- Name: TABLE "Degree_Program"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public."Degree_Program" IS 'List of Degree Programs';


--
-- Name: Degree_Program_degree_prog_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Degree_Program" ALTER COLUMN degree_prog_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Degree_Program_degree_prog_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Invitation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Invitation" (
    recepient_id uuid NOT NULL,
    study_group_id bigint NOT NULL,
    invite_date timestamp without time zone NOT NULL,
    expiration_duration integer,
    expiration_date timestamp without time zone
);


ALTER TABLE public."Invitation" OWNER TO postgres;

--
-- Name: TABLE "Invitation"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public."Invitation" IS 'Table that contains invitation data';


--
-- Name: Meeting; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Meeting" (
    study_group_id bigint NOT NULL,
    meeting_id bigint NOT NULL,
    start_time timestamp without time zone NOT NULL,
    end_time timestamp without time zone,
    location extensions.geography
);


ALTER TABLE public."Meeting" OWNER TO postgres;

--
-- Name: TABLE "Meeting"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public."Meeting" IS 'Meeting information for study group';


--
-- Name: Meeting_meeting_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Meeting" ALTER COLUMN meeting_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Meeting_meeting_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Study_Group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Study_Group" (
    study_group_id bigint NOT NULL,
    subject_code text DEFAULT ''::text NOT NULL,
    visibility public.visibility NOT NULL,
    join_method public.join_method NOT NULL,
    leader_id uuid NOT NULL
);


ALTER TABLE public."Study_Group" OWNER TO postgres;

--
-- Name: TABLE "Study_Group"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public."Study_Group" IS 'Study group information';


--
-- Name: Study_Group_Members; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Study_Group_Members" (
    study_group_id bigint NOT NULL,
    member_id uuid NOT NULL
);


ALTER TABLE public."Study_Group_Members" OWNER TO postgres;

--
-- Name: TABLE "Study_Group_Members"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public."Study_Group_Members" IS 'Table of study group members';


--
-- Name: Study_Group_Members_study_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Study_Group_Members" ALTER COLUMN study_group_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Study_Group_Members_study_group_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Study_Group_study_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Study_Group" ALTER COLUMN study_group_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Study_Group_study_group_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Subject; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Subject" (
    subject_code text NOT NULL,
    subject_name text NOT NULL
);


ALTER TABLE public."Subject" OWNER TO postgres;

--
-- Name: TABLE "Subject"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public."Subject" IS 'List of Subjects';


--
-- Name: User; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."User" (
    user_id uuid NOT NULL,
    year_level smallint DEFAULT '1'::smallint NOT NULL,
    f_name text NOT NULL,
    l_name text NOT NULL,
    username text NOT NULL,
    email character varying NOT NULL,
    profile_picture text NOT NULL,
    degree_prog_id integer NOT NULL
);


ALTER TABLE public."User" OWNER TO postgres;

--
-- Name: TABLE "User"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public."User" IS 'This table contains user data';


--
-- Data for Name: Degree_Program; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Degree_Program" (degree_prog_id, degree_prog_name) FROM stdin;
\.


--
-- Data for Name: Invitation; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Invitation" (recepient_id, study_group_id, invite_date, expiration_duration, expiration_date) FROM stdin;
\.


--
-- Data for Name: Meeting; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Meeting" (study_group_id, meeting_id, start_time, end_time, location) FROM stdin;
\.


--
-- Data for Name: Study_Group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Study_Group" (study_group_id, subject_code, visibility, join_method, leader_id) FROM stdin;
\.


--
-- Data for Name: Study_Group_Members; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Study_Group_Members" (study_group_id, member_id) FROM stdin;
\.


--
-- Data for Name: Subject; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Subject" (subject_code, subject_name) FROM stdin;
\.


--
-- Data for Name: User; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."User" (user_id, year_level, f_name, l_name, username, email, profile_picture, degree_prog_id) FROM stdin;
\.


--
-- Name: Degree_Program_degree_prog_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Degree_Program_degree_prog_id_seq"', 1, false);


--
-- Name: Meeting_meeting_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Meeting_meeting_id_seq"', 1, false);


--
-- Name: Study_Group_Members_study_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Study_Group_Members_study_group_id_seq"', 1, false);


--
-- Name: Study_Group_study_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Study_Group_study_group_id_seq"', 1, false);


--
-- Name: Degree_Program Degree_Program_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Degree_Program"
    ADD CONSTRAINT "Degree_Program_pkey" PRIMARY KEY (degree_prog_id);


--
-- Name: Invitation Invitation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Invitation"
    ADD CONSTRAINT "Invitation_pkey" PRIMARY KEY (recepient_id, study_group_id);


--
-- Name: Meeting Meeting_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Meeting"
    ADD CONSTRAINT "Meeting_pkey" PRIMARY KEY (study_group_id, meeting_id);


--
-- Name: Study_Group_Members Study_Group_Members_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Study_Group_Members"
    ADD CONSTRAINT "Study_Group_Members_pkey" PRIMARY KEY (study_group_id, member_id);


--
-- Name: Study_Group Study_Group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Study_Group"
    ADD CONSTRAINT "Study_Group_pkey" PRIMARY KEY (study_group_id);


--
-- Name: Subject Subject_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Subject"
    ADD CONSTRAINT "Subject_pkey" PRIMARY KEY (subject_code);


--
-- Name: User User_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."User"
    ADD CONSTRAINT "User_email_key" UNIQUE (email);


--
-- Name: User User_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."User"
    ADD CONSTRAINT "User_pkey" PRIMARY KEY (user_id);


--
-- Name: User User_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."User"
    ADD CONSTRAINT "User_username_key" UNIQUE (username);


--
-- Name: Invitation Invitation_recepient_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Invitation"
    ADD CONSTRAINT "Invitation_recepient_id_fkey" FOREIGN KEY (recepient_id) REFERENCES public."User"(user_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: Invitation Invitation_study_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Invitation"
    ADD CONSTRAINT "Invitation_study_group_id_fkey" FOREIGN KEY (study_group_id) REFERENCES public."Study_Group"(study_group_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: Meeting Meeting_study_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Meeting"
    ADD CONSTRAINT "Meeting_study_group_id_fkey" FOREIGN KEY (study_group_id) REFERENCES public."Study_Group"(study_group_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: Study_Group_Members Study_Group_Members_member_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Study_Group_Members"
    ADD CONSTRAINT "Study_Group_Members_member_id_fkey" FOREIGN KEY (member_id) REFERENCES public."User"(user_id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: Study_Group_Members Study_Group_Members_study_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Study_Group_Members"
    ADD CONSTRAINT "Study_Group_Members_study_group_id_fkey" FOREIGN KEY (study_group_id) REFERENCES public."Study_Group"(study_group_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: Study_Group Study_Group_leader_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Study_Group"
    ADD CONSTRAINT "Study_Group_leader_id_fkey" FOREIGN KEY (leader_id) REFERENCES public."User"(user_id);


--
-- Name: Study_Group Study_Group_subject_code_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Study_Group"
    ADD CONSTRAINT "Study_Group_subject_code_fkey" FOREIGN KEY (subject_code) REFERENCES public."Subject"(subject_code);


--
-- Name: User User_degree_prog_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."User"
    ADD CONSTRAINT "User_degree_prog_id_fkey" FOREIGN KEY (degree_prog_id) REFERENCES public."Degree_Program"(degree_prog_id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: User User_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."User"
    ADD CONSTRAINT "User_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: Degree_Program; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public."Degree_Program" ENABLE ROW LEVEL SECURITY;

--
-- Name: Invitation; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public."Invitation" ENABLE ROW LEVEL SECURITY;

--
-- Name: Meeting; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public."Meeting" ENABLE ROW LEVEL SECURITY;

--
-- Name: Study_Group; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public."Study_Group" ENABLE ROW LEVEL SECURITY;

--
-- Name: Study_Group_Members; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public."Study_Group_Members" ENABLE ROW LEVEL SECURITY;

--
-- Name: Subject; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public."Subject" ENABLE ROW LEVEL SECURITY;

--
-- Name: User; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public."User" ENABLE ROW LEVEL SECURITY;

--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT USAGE ON SCHEMA public TO postgres;
GRANT USAGE ON SCHEMA public TO anon;
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT USAGE ON SCHEMA public TO service_role;


--
-- Name: TABLE "Degree_Program"; Type: ACL; Schema: public; Owner: postgres
--

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public."Degree_Program" TO anon;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public."Degree_Program" TO authenticated;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public."Degree_Program" TO service_role;


--
-- Name: SEQUENCE "Degree_Program_degree_prog_id_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public."Degree_Program_degree_prog_id_seq" TO anon;
GRANT ALL ON SEQUENCE public."Degree_Program_degree_prog_id_seq" TO authenticated;
GRANT ALL ON SEQUENCE public."Degree_Program_degree_prog_id_seq" TO service_role;


--
-- Name: TABLE "Invitation"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public."Invitation" TO anon;
GRANT ALL ON TABLE public."Invitation" TO authenticated;
GRANT ALL ON TABLE public."Invitation" TO service_role;


--
-- Name: TABLE "Meeting"; Type: ACL; Schema: public; Owner: postgres
--

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public."Meeting" TO anon;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public."Meeting" TO authenticated;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public."Meeting" TO service_role;


--
-- Name: SEQUENCE "Meeting_meeting_id_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public."Meeting_meeting_id_seq" TO anon;
GRANT ALL ON SEQUENCE public."Meeting_meeting_id_seq" TO authenticated;
GRANT ALL ON SEQUENCE public."Meeting_meeting_id_seq" TO service_role;


--
-- Name: TABLE "Study_Group"; Type: ACL; Schema: public; Owner: postgres
--

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public."Study_Group" TO anon;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public."Study_Group" TO authenticated;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public."Study_Group" TO service_role;


--
-- Name: TABLE "Study_Group_Members"; Type: ACL; Schema: public; Owner: postgres
--

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public."Study_Group_Members" TO anon;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public."Study_Group_Members" TO authenticated;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public."Study_Group_Members" TO service_role;


--
-- Name: SEQUENCE "Study_Group_Members_study_group_id_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public."Study_Group_Members_study_group_id_seq" TO anon;
GRANT ALL ON SEQUENCE public."Study_Group_Members_study_group_id_seq" TO authenticated;
GRANT ALL ON SEQUENCE public."Study_Group_Members_study_group_id_seq" TO service_role;


--
-- Name: SEQUENCE "Study_Group_study_group_id_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public."Study_Group_study_group_id_seq" TO anon;
GRANT ALL ON SEQUENCE public."Study_Group_study_group_id_seq" TO authenticated;
GRANT ALL ON SEQUENCE public."Study_Group_study_group_id_seq" TO service_role;


--
-- Name: TABLE "Subject"; Type: ACL; Schema: public; Owner: postgres
--

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public."Subject" TO anon;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public."Subject" TO authenticated;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public."Subject" TO service_role;


--
-- Name: TABLE "User"; Type: ACL; Schema: public; Owner: postgres
--

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public."User" TO anon;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public."User" TO authenticated;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public."User" TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO service_role;


--
-- PostgreSQL database dump complete
--

\unrestrict Xq245Z00PuPHL7yuWKhzsormDXDzPhwMm8lonOcMzczwt8ChGDlo4Q0xeVrzII9

