ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
overrides:
  '@langchain/core@<0.3.80': '>=0.3.80'
  langsmith@<0.6.0: '>=0.6.0'
  langsmith@<=0.5.17: '>=0.5.18'
  langsmith@<=0.5.18: '>=0.5.19'
  next@>=16.0.0 <16.2.6: '>=16.2.6'
  postcss@<8.5.10: '>=8.5.10'
  tar@<7.5.7: '>=7.5.7'
  tar@<7.5.8: '>=7.5.8'
  tar@<=7.5.10: '>=7.5.11'
  tar@<=7.5.2: '>=7.5.3'
  tar@<=7.5.3: '>=7.5.4'
  tar@<=7.5.9: '>=7.5.10'
  tmp@<=0.2.3: '>=0.2.4'
