--
-- PostgreSQL database dump
--

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.10 (Ubuntu 17.10-1.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Extension: postgis
--
CREATE extension postgis WITH SCHEMA "extensions";

--
-- Name: join_method; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.join_method AS ENUM (
    'public',
    'request_join',
    'invite_only'
);


ALTER TYPE public.join_method OWNER TO postgres;

--
-- Name: TYPE join_method; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TYPE public.join_method IS 'Join method of study groups';


--
-- Name: visibility; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.visibility AS ENUM (
    'public',
    'private'
);


ALTER TYPE public.visibility OWNER TO postgres;

--
-- Name: TYPE visibility; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TYPE public.visibility IS 'Visibility of study groups';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Degree_Program; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Degree_Program" (
    degree_prog_id bigint NOT NULL,
    degree_prog_name text NOT NULL
);


ALTER TABLE public."Degree_Program" OWNER TO postgres;

--
-- Name: Degree_Program_degree_prog_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Degree_Program" ALTER COLUMN degree_prog_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Degree_Program_degree_prog_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Invitation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Invitation" (
    user_id uuid NOT NULL,
    study_group_id bigint NOT NULL,
    invite_date timestamp without time zone NOT NULL,
    expiration_duration bigint
);


ALTER TABLE public."Invitation" OWNER TO postgres;

--
-- Name: TABLE "Invitation"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public."Invitation" IS 'Table with invitation information';


--
-- Name: Join_Requests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Join_Requests" (
    study_group_id bigint NOT NULL,
    user_id uuid NOT NULL
);


ALTER TABLE public."Join_Requests" OWNER TO postgres;

--
-- Name: TABLE "Join_Requests"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public."Join_Requests" IS 'This table contains information from users requesting to join a study group';


--
-- Name: Join_Requests_study_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Join_Requests" ALTER COLUMN study_group_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Join_Requests_study_group_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Meeting; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Meeting" (
    study_group_id bigint NOT NULL,
    meeting_id bigint NOT NULL,
    start_time timestamp without time zone NOT NULL,
    end_time timestamp without time zone NOT NULL,
    location_coord extensions.geography
);


ALTER TABLE public."Meeting" OWNER TO postgres;

--
-- Name: TABLE "Meeting"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public."Meeting" IS 'Meeting information for study groups';


--
-- Name: Study_Group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Study_Group" (
    study_group_id bigint NOT NULL,
    subject_id text DEFAULT ''::text NOT NULL,
    join_method public.join_method NOT NULL,
    visibility public.visibility NOT NULL,
    leader_id uuid NOT NULL
);


ALTER TABLE public."Study_Group" OWNER TO postgres;

--
-- Name: TABLE "Study_Group"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public."Study_Group" IS 'Table of study groups made by users';


--
-- Name: Study_Group_Members; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Study_Group_Members" (
    user_id uuid NOT NULL,
    study_group_id bigint NOT NULL
);


ALTER TABLE public."Study_Group_Members" OWNER TO postgres;

--
-- Name: TABLE "Study_Group_Members"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public."Study_Group_Members" IS 'Table containing study group members';


--
-- Name: Study_Group_study_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Study_Group" ALTER COLUMN study_group_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Study_Group_study_group_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Subject; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Subject" (
    subject_code text NOT NULL,
    subject_name text NOT NULL,
    degree_prog_id bigint NOT NULL
);


ALTER TABLE public."Subject" OWNER TO postgres;

--
-- Name: TABLE "Subject"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public."Subject" IS 'Table of subjects taken by students';


--
-- Name: User; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."User" (
    user_id uuid NOT NULL,
    year_level smallint NOT NULL,
    f_name text NOT NULL,
    l_name text NOT NULL,
    username text NOT NULL,
    profile_picture text NOT NULL,
    degree_program bigint NOT NULL
);


ALTER TABLE public."User" OWNER TO postgres;

--
-- Name: TABLE "User"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public."User" IS 'Table of users';


--
-- Name: Degree_Program Degree_Program_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Degree_Program"
    ADD CONSTRAINT "Degree_Program_pkey" PRIMARY KEY (degree_prog_id);


--
-- Name: Invitation Invitation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Invitation"
    ADD CONSTRAINT "Invitation_pkey" PRIMARY KEY (user_id, study_group_id);


--
-- Name: Join_Requests Join_Requests_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Join_Requests"
    ADD CONSTRAINT "Join_Requests_pkey" PRIMARY KEY (study_group_id, user_id);


--
-- Name: Meeting Meeting_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Meeting"
    ADD CONSTRAINT "Meeting_pkey" PRIMARY KEY (study_group_id, meeting_id);


--
-- Name: Study_Group_Members Study_Group_Members_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Study_Group_Members"
    ADD CONSTRAINT "Study_Group_Members_pkey" PRIMARY KEY (user_id, study_group_id);


--
-- Name: Study_Group Study_Group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Study_Group"
    ADD CONSTRAINT "Study_Group_pkey" PRIMARY KEY (study_group_id);


--
-- Name: Subject Subject_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Subject"
    ADD CONSTRAINT "Subject_pkey" PRIMARY KEY (subject_code);


--
-- Name: User User_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."User"
    ADD CONSTRAINT "User_pkey" PRIMARY KEY (user_id);


--
-- Name: User User_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."User"
    ADD CONSTRAINT "User_username_key" UNIQUE (username);


--
-- Name: Invitation Invitation_study_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Invitation"
    ADD CONSTRAINT "Invitation_study_group_id_fkey" FOREIGN KEY (study_group_id) REFERENCES public."Study_Group"(study_group_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: Invitation Invitation_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Invitation"
    ADD CONSTRAINT "Invitation_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public."User"(user_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: Join_Requests Join_Requests_study_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Join_Requests"
    ADD CONSTRAINT "Join_Requests_study_group_id_fkey" FOREIGN KEY (study_group_id) REFERENCES public."Study_Group"(study_group_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: Join_Requests Join_Requests_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Join_Requests"
    ADD CONSTRAINT "Join_Requests_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public."User"(user_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: Meeting Meeting_study_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Meeting"
    ADD CONSTRAINT "Meeting_study_group_id_fkey" FOREIGN KEY (study_group_id) REFERENCES public."Study_Group"(study_group_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: Study_Group_Members Study_Group_Members_study_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Study_Group_Members"
    ADD CONSTRAINT "Study_Group_Members_study_group_id_fkey" FOREIGN KEY (study_group_id) REFERENCES public."Study_Group"(study_group_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: Study_Group_Members Study_Group_Members_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Study_Group_Members"
    ADD CONSTRAINT "Study_Group_Members_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public."User"(user_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: Study_Group Study_Group_leader_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Study_Group"
    ADD CONSTRAINT "Study_Group_leader_id_fkey" FOREIGN KEY (leader_id) REFERENCES public."User"(user_id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: Study_Group Study_Group_subject_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Study_Group"
    ADD CONSTRAINT "Study_Group_subject_id_fkey" FOREIGN KEY (subject_id) REFERENCES public."Subject"(subject_code) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: Subject Subject_degree_prog_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Subject"
    ADD CONSTRAINT "Subject_degree_prog_id" FOREIGN KEY (degree_prog_id) REFERENCES public."Degree_Program"(degree_prog_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: User User_degree_program_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."User"
    ADD CONSTRAINT "User_degree_program_fkey" FOREIGN KEY (degree_program) REFERENCES public."Degree_Program"(degree_prog_id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: User User_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."User"
    ADD CONSTRAINT "User_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: Degree_Program Authenticated users can see degree programs; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Authenticated users can see degree programs" ON public."Degree_Program" FOR SELECT TO authenticated USING ((( SELECT auth.uid() AS uid) IN ( SELECT "User".user_id
   FROM public."User")));


--
-- Name: Subject Authenticated users can see subjects; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Authenticated users can see subjects" ON public."Subject" FOR SELECT TO authenticated USING ((( SELECT auth.uid() AS uid) IN ( SELECT "User".user_id
   FROM public."User")));


--
-- Name: Degree_Program; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public."Degree_Program" ENABLE ROW LEVEL SECURITY;

--
-- Name: Invitation; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public."Invitation" ENABLE ROW LEVEL SECURITY;

--
-- Name: Join_Requests; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public."Join_Requests" ENABLE ROW LEVEL SECURITY;

--
-- Name: Study_Group Leader and members of a study group can see it's details; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Leader and members of a study group can see it's details" ON public."Study_Group" FOR SELECT TO authenticated USING (((( SELECT auth.uid() AS uid) IN ( SELECT "Study_Group_Members".user_id
   FROM public."Study_Group_Members")) OR (( SELECT auth.uid() AS uid) = leader_id)));


--
-- Name: Study_Group Leaders can delete study groups; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Leaders can delete study groups" ON public."Study_Group" FOR DELETE TO authenticated USING ((( SELECT auth.uid() AS uid) = leader_id));


--
-- Name: Join_Requests Leaders can interact with join requests; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Leaders can interact with join requests" ON public."Join_Requests" FOR DELETE TO authenticated USING (( SELECT (auth.uid() IN ( SELECT "Study_Group".leader_id
           FROM public."Study_Group"
          WHERE ("Study_Group".study_group_id = "Join_Requests".study_group_id)))));


--
-- Name: Study_Group_Members Leaders can remove members from their study group; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Leaders can remove members from their study group" ON public."Study_Group_Members" FOR DELETE TO authenticated USING ((( SELECT auth.uid() AS uid) IN ( SELECT "Study_Group".leader_id
   FROM public."Study_Group"
  WHERE ("Study_Group".study_group_id = "Study_Group_Members".study_group_id))));


--
-- Name: Invitation Leaders can send invitations to user; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Leaders can send invitations to user" ON public."Invitation" FOR INSERT TO authenticated WITH CHECK ((( SELECT auth.uid() AS uid) IN ( SELECT "Study_Group".leader_id
   FROM public."Study_Group")));


--
-- Name: Study_Group Leaders can update study group details; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Leaders can update study group details" ON public."Study_Group" FOR UPDATE TO authenticated USING ((( SELECT auth.uid() AS uid) = leader_id));


--
-- Name: Join_Requests Leaders can view join requests; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Leaders can view join requests" ON public."Join_Requests" FOR SELECT TO authenticated USING (( SELECT (auth.uid() IN ( SELECT "Study_Group".leader_id
           FROM public."Study_Group"
          WHERE ("Study_Group".study_group_id = "Join_Requests".study_group_id)))));


--
-- Name: Invitation Leaders can view their sent invitations; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Leaders can view their sent invitations" ON public."Invitation" FOR SELECT TO authenticated USING ((( SELECT auth.uid() AS uid) IN ( SELECT "Study_Group".leader_id
   FROM public."Study_Group"
  WHERE ("Invitation".study_group_id = "Study_Group".study_group_id))));


--
-- Name: Study_Group_Members Leaders can view who are the members of their study groups; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Leaders can view who are the members of their study groups" ON public."Study_Group_Members" FOR SELECT TO authenticated USING ((( SELECT auth.uid() AS uid) IN ( SELECT "Study_Group".leader_id
   FROM public."Study_Group"
  WHERE ("Study_Group".study_group_id = "Study_Group_Members".study_group_id))));


--
-- Name: Meeting; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public."Meeting" ENABLE ROW LEVEL SECURITY;

--
-- Name: Study_Group Public study groups can be seen by authenticated users; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Public study groups can be seen by authenticated users" ON public."Study_Group" FOR SELECT TO authenticated USING (((( SELECT auth.uid() AS uid) IN ( SELECT "User".user_id
   FROM public."User")) AND (visibility = 'public'::public.visibility)));


--
-- Name: Study_Group; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public."Study_Group" ENABLE ROW LEVEL SECURITY;

--
-- Name: Study_Group_Members; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public."Study_Group_Members" ENABLE ROW LEVEL SECURITY;

--
-- Name: Subject; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public."Subject" ENABLE ROW LEVEL SECURITY;

--
-- Name: User; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public."User" ENABLE ROW LEVEL SECURITY;

--
-- Name: User Users can add their own account; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Users can add their own account" ON public."User" FOR INSERT TO authenticated WITH CHECK ((( SELECT auth.uid() AS uid) = user_id));


--
-- Name: User Users can delete their own accounts; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Users can delete their own accounts" ON public."User" FOR DELETE TO authenticated USING ((( SELECT auth.uid() AS uid) = user_id));


--
-- Name: Invitation Users can interact with their own invitations; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Users can interact with their own invitations" ON public."Invitation" FOR DELETE TO authenticated USING ((( SELECT auth.uid() AS uid) = user_id));


--
-- Name: Study_Group_Members Users can leave their study groups; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Users can leave their study groups" ON public."Study_Group_Members" FOR DELETE TO authenticated USING ((( SELECT auth.uid() AS uid) = user_id));


--
-- Name: Join_Requests Users can request to join request_join study groups; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Users can request to join request_join study groups" ON public."Join_Requests" FOR INSERT TO authenticated WITH CHECK ((( SELECT auth.uid() AS uid) = user_id));


--
-- Name: Join_Requests Users can retract join requests; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Users can retract join requests" ON public."Join_Requests" FOR DELETE TO authenticated USING ((( SELECT auth.uid() AS uid) = user_id));


--
-- Name: User Users can update their own account details; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Users can update their own account details" ON public."User" FOR UPDATE TO authenticated USING ((( SELECT auth.uid() AS uid) = user_id));


--
-- Name: User Users can view their own data; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Users can view their own data" ON public."User" FOR SELECT TO authenticated USING ((( SELECT auth.uid() AS uid) = user_id));


--
-- Name: Invitation Users can view their won invitations; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Users can view their won invitations" ON public."Invitation" FOR SELECT TO authenticated USING ((( SELECT auth.uid() AS uid) = user_id));


--
-- Name: Study_Group_Members Users can view which study groups they are a member of; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Users can view which study groups they are a member of" ON public."Study_Group_Members" FOR SELECT TO authenticated USING ((( SELECT auth.uid() AS uid) = user_id));


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT USAGE ON SCHEMA public TO postgres;
GRANT USAGE ON SCHEMA public TO anon;
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT USAGE ON SCHEMA public TO service_role;


--
-- Name: TABLE "Degree_Program"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public."Degree_Program" TO service_role;
GRANT SELECT ON TABLE public."Degree_Program" TO authenticated;


--
-- Name: SEQUENCE "Degree_Program_degree_prog_id_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public."Degree_Program_degree_prog_id_seq" TO anon;
GRANT ALL ON SEQUENCE public."Degree_Program_degree_prog_id_seq" TO authenticated;
GRANT ALL ON SEQUENCE public."Degree_Program_degree_prog_id_seq" TO service_role;


--
-- Name: TABLE "Invitation"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public."Invitation" TO service_role;
GRANT ALL ON TABLE public."Invitation" TO authenticated;


--
-- Name: TABLE "Join_Requests"; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public."Join_Requests" TO service_role;
GRANT ALL ON TABLE public."Join_Requests" TO authenticated;


--
-- Name: SEQUENCE "Join_Requests_study_group_id_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public."Join_Requests_study_group_id_seq" TO anon;
GRANT ALL ON SEQUENCE public."Join_Requests_study_group_id_seq" TO authenticated;
GRANT ALL ON SEQUENCE public."Join_Requests_study_group_id_seq" TO service_role;


--
-- Name: TABLE "Meeting"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public."Meeting" TO service_role;
GRANT ALL ON TABLE public."Meeting" TO authenticated;


--
-- Name: TABLE "Study_Group"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public."Study_Group" TO service_role;
GRANT ALL ON TABLE public."Study_Group" TO authenticated;


--
-- Name: TABLE "Study_Group_Members"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public."Study_Group_Members" TO service_role;
GRANT ALL ON TABLE public."Study_Group_Members" TO authenticated;


--
-- Name: SEQUENCE "Study_Group_study_group_id_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public."Study_Group_study_group_id_seq" TO anon;
GRANT ALL ON SEQUENCE public."Study_Group_study_group_id_seq" TO authenticated;
GRANT ALL ON SEQUENCE public."Study_Group_study_group_id_seq" TO service_role;


--
-- Name: TABLE "Subject"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public."Subject" TO service_role;
GRANT SELECT ON TABLE public."Subject" TO authenticated;


--
-- Name: TABLE "User"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public."User" TO service_role;
GRANT ALL ON TABLE public."User" TO authenticated;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO service_role;


--
-- PostgreSQL database dump complete
--
